services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: o6_hr
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
